server:
  port: 9888
  servlet:
    context-path: /api/goplan/
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  jwt:
    secret: gogofndgogosafe#!
  datasource:
    url: jdbc:mariadb://116.120.58.222:3306/goPlan_KB?serverTimezone=Asia/Seoul
    username: goplan
    password: goplan0@
    datasource: driver-class-name=org.mariadb.jdbc.Driver
    hikari:max-lifetime: 177000 #177초, hikari는 RDS wait_timeout(180초) 보다 2 ~ 3초 정도 짧게 줄 것을 권장
  spring-doc:
    api-docs:
      groups:
        enabled: true
    swagger-ui:
      path: /swagger-ui.html
      displayRequestDuration: true
      groups-order: DESC
  jpa:
    show-sql: false
    open-in-view: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000

project:
  properties:
    firebase-create-scoped: "https://www.googleapis.com/auth/firebase.messaging"
    firebase-topic: "diet_record_notification"

app:
  filePath: /home/goplan/images
  baseUrl: http://10.0.2.101:57509

firebaseKey: /home/goplan/kb/firebase/kb-flutter-8c87e-firebase-adminsdk-7yzva-e3283f39a5.json

hash: gogofndgoplan#!%
